env:
  browser: true
  node: true
  es6: true

plugins:
  - prettier

extends:
  - prettier

rules:
  handle-callback-err: 2
  keyword-spacing: 2
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-lonely-if: 2
  no-shadow: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {args: none}]
  no-var: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prettier/prettier: 2
  sort-imports: 2
  sort-keys: [2, asc, {caseSensitive: true, natural: true}]
  sort-vars: 2
  space-before-blocks: 2
  strict: [2, global]
  valid-jsdoc: [2, {requireParamDescription: false, requireReturnDescription: false}]
